(define (make-monochrome-theme background foreground)
  (define t (make-theme))
  (theme-set-color! t 'prompt foreground)
  (theme-set-css! t 'prompt "font-weight: bold;")
  (theme-set-color! t 'error foreground)
  (theme-set-css! t 'error "font-weight: bold;")
  (theme-set-color! t 'link foreground)
  (theme-set-color! t 'link-hover foreground)
  (theme-set-css! t 'link-hover "text-decoration: underline;")
  (theme-set-color! t 'status foreground)
  (theme-set-color! t 'spec-keyword foreground)
  (theme-set-css! t 'spec-keyword "font-weight: bold;")
  (theme-set-color! t 'extra-keyword foreground)
  (theme-set-css! t 'extra-keyword "font-weight: bold;")
  (theme-set-color! t 'procedure foreground)
  (theme-set-css! t 'procedure "font-weight: bold;")
  (theme-set-color! t 'boolean foreground)
  (theme-set-color! t 'text foreground)
  (theme-set-color! t 'number foreground)
  (theme-set-color! t 'symbol foreground)
  (theme-set-color! t 'string foreground)
  (theme-set-color! t 'comment foreground)
  (theme-set-css! t 'comment "font-style: italic;")
  (theme-set-color! t 'render foreground)
  (theme-set-color! t 'return-value foreground)
  (theme-set-color! t 'arrow foreground)
  (theme-set-color! t 'button background)
  (theme-set-color! t 'button-text foreground)
  (theme-set-color! t 'button-hover foreground)
  (theme-set-color! t 'button-text-hover background)
  (theme-set-color! t 'async-log foreground)
  (theme-set-css! t 'async-log "font-style: italic;")

  (theme-set-color! t 'background background)
  (theme-set-color! t 'current-frame background)
  (theme-set-css! t 'current-frame (string-append "border: 0.125em solid " (color->css foreground) ";"))
  (theme-set-color! t 'other-frame background)
  (theme-set-css! t 'other-frame (string-append "border: 0.125em dashed " (color->css foreground) ";"))
  (theme-set-color! t 'pair background)
  (theme-set-css! t 'pair (string-append "border: 0.125em solid " (color->css foreground) ";"))
  (theme-set-color! t 'vector background)
  (theme-set-css! t 'vector (string-append "border: 0.125em solid " (color->css foreground) ";"))
  (theme-set-color! t 'promise background)
  (theme-set-css! t 'promise (string-append "border: 0.125em solid " (color->css foreground) ";"))
  (theme-set-color! t 'async-block background)
  (theme-set-css! t 'async-block (string-append "border: 0.125em solid " (color->css foreground) ";"))

  (theme-set-css! t 'button (string-append "border: 0.125em solid " (color->css foreground) ";"))
  (theme-set-css! t 'button-hover (string-append "border: 0.125em solid " (color->css foreground) ";"))
  t)

(apply-theme (make-monochrome-theme (hex "#fff") (hex "#000")))
