(define (make-solarized-theme)
  (define base03 (hex "#002b36"))
  (define base02 (hex "#074642"))
  (define base01 (hex "#586e75"))
  (define base00 (hex "#657b83"))
  (define base0 (hex "#839496"))
  (define base1 (hex "#93a1a1"))
  (define base2 (hex "#eee8d5"))
  (define base3 (hex "#fdf6e3"))
  (define yellow (hex "#b58900"))
  (define orange (hex "#cb4b16"))
  (define red (hex "#dc322f"))
  (define magenta (hex "#d33682"))
  (define violet (hex "#6c71c4"))
  (define blue (hex "#268bd2"))
  (define cyan (hex "#2aa198"))
  (define green (hex "#859900"))

  (define t (make-theme))
  (theme-set-color! t 'prompt green)
  (theme-set-color! t 'error red)
  (theme-set-color! t 'link blue)
  (theme-set-color! t 'link-hover cyan)
  (theme-set-color! t 'status base00)
  (theme-set-color! t 'spec-keyword blue)
  (theme-set-color! t 'extra-keyword green)
  (theme-set-color! t 'procedure base1)
  (theme-set-color! t 'boolean yellow)
  (theme-set-color! t 'text base1)
  (theme-set-color! t 'number magenta)
  (theme-set-color! t 'symbol base1)
  (theme-set-color! t 'string cyan)
  (theme-set-color! t 'comment base00)
  (theme-set-css! t 'comment "font-style: italic;")
  (theme-set-color! t 'render base3)
  (theme-set-color! t 'return-value base3)
  (theme-set-color! t 'arrow base1)
  (theme-set-color! t 'button blue)
  (theme-set-color! t 'button-text base3)
  (theme-set-color! t 'button-hover cyan)
  (theme-set-color! t 'button-text-hover base3)
  (theme-set-color! t 'async-log yellow)
  (theme-set-css! t 'async-log "font-style: italic;")
  
  (theme-set-color! t 'background base03)
  (theme-set-color! t 'current-frame blue)
  (theme-set-color! t 'other-frame base01)
  (theme-set-color! t 'pair violet)
  (define border (string-append "border: 0.125em solid " (color->css base03) ";"))
  (theme-set-css! t 'pair border)
  (theme-set-color! t 'vector orange)
  (theme-set-css! t 'vector border)
  (theme-set-color! t 'promise green)
  (theme-set-css! t 'promise border)
  (theme-set-color! t 'async-block yellow)
  (theme-set-css! t 'async-block border)
  t)

(define imported-theme (make-solarized-theme))
